semantics:
  available:
    - name: "dspace.identifier.citation"
      path: "/sections/publicationStep/dc.identifier.citation"
    - name: "dspace.identifier.govdoc"
      path: "/sections/publicationStep/dc.identifier.govdoc"
    - name: "dspace.identifier.isbn"
      path: "/sections/publicationStep/dc.identifier.isbn"
    - name: "dspace.identifier.ismn"
      path: "/sections/publicationStep/dc.identifier.ismn"
    - name: "dspace.identifier.other"
      path: "/sections/publicationStep/dc.identifier.other"
    - name: "dspace.identifier.uri"
      path: "/sections/publicationStep/dc.identifier.uri"
    - name: "dspace.description"
      path: "/sections/traditionalpagetwo/dc.description"
    - name: "dspace.description.provenance"
      path: "/metadata/dc.description.provenance"
    - name: "dspace.description.sponsorship"
      path: "/sections/traditionalpagetwo/dc.description.sponsorship"
    - name: "dspace.title.alternative"
      path: "/sections/publicationStep/dc.title.alternative"
    - name: "dspace.publisher"
      path: "/sections/publicationStep/dc.publisher"
    - name: "dspace.type"
      path: "/sections/publicationStep/dc.type"
    - name: "dspace.language"
      path: "/sections/publicationStep/dc.language.iso"
    - name: "dspace.contributor.author"
      path: "/sections/publicationStep/dc.contributor.author"
    - name: "dspace.date.accessioned"
      path: "/metadata/dc.date.accessioned"
    - name: "dspace.date.available"
      path: "/metadata/dc.date.available"